### ISSUE TITLE
[1.20.4] [Fabric] CTD on attempt to open mod menu

### ISSUE THREAD

**Issue by monkeyzone456** [Octo-Studios/nerb#10] opened 2024-02-11 01:52 UTC
[crash-2024-02-10_18.43.54-client.txt](https://github.com/SSKirillSS/nerb/files/14231013/crash-2024-02-10_18.43.54-client.txt)

Consistent, just open game, click mods (in game, or at main menu both Crash), 

I did a binary search its definetly NERB.

Mods

[modlist.txt](https://github.com/SSKirillSS/nerb/files/14231032/modlist.txt)

**Comment by lnminh1411** [comment] 2024-02-16 14:52
I have the same problem also.

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_8666.comp_1604()" because "image.field_45356" is null

**Comment by viktordimov** [comment] 2024-02-19 05:33
Same issue.
[[052944] [Render threadERROR] Report.txt](https://github.com/SSKirillSS/nerb/files/14326755/052944.Render.threadERROR.Report.txt)
I tested all mods and this is definitely the one that causes the issue. 
[Modlist.txt](https://github.com/SSKirillSS/nerb/files/14326768/Modlist.txt)

**Comment by sciguyryan** [comment] 2024-03-24 18:35
I can confirm this is still an issue, it took me a while to track this one down though!

**Comment by GarrixonWasTaken** [comment] 2024-04-05 21:06
Can also confirm I have this issue

**Comment by xMdb** [comment] 2024-04-25 02:48
Can confirm this issue. Luckily someone on Reddit tracked it down for me: https://www.reddit.com/r/fabricmc/comments/1b9y8hs/mod_menu_1204_crash_the_game_when_i_try_to_open_it/

Crash log: https://mclo.gs/L9LD5RW

**Comment by SSKirillSS** [comment] 2024-05-25 20:43
Should be fixed now. Thanks for the info!

**Closed as completed by SSKirillSS** 2024-05-25 20:43 UTC
